name: Python-app

on:
  schedule:
    - cron: '00 23 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: Send morning to your girlfriend

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies and run script
      run: |
        pip install -r ./requirements.txt
        python ./main.py
